stages:
  - mirror
  - build
  - deploy
  - notify
  - cleanup


mirror:
  stage: mirror
  only:
    refs:
      - /^(main.*)$/
  script:
    - chmod +x ./ci/deliver.sh
    - ./ci/mirror.sh
  tags:
    - amirplatform



build_image:
  stage: build
  only:
    refs:
      - /^(main.*)$/
    changes:
      - controllers/**/**
      - middlewares/**/**
      - models/**/**
      - routes/**/**
      - utils/**/**
      - app.js
      - server.js
      - Dockerfile
      - docker-compose-build.yml
      - docker-compose.yml
      - package-lock.json
      - package.json
      - git_script.sh
  tags:
    - imagesbuilder
  script:
    - chmod +x ./ci/deliver.sh
    - ./ci/deliver.sh



deploy_image:
  stage: deploy
  script:
    - chmod +x ./ci/deploy.sh
    - ./ci/deploy.sh
  only:
    refs:
      - /^(main.*)$/
    changes:
      - controllers/**/**
      - middlewares/**/**
      - models/**/**
      - routes/**/**
      - utils/**/**
      - app.js
      - server.js
      - Dockerfile
      - docker-compose-build.yml
      - docker-compose.yml
      - package-lock.json
      - package.json
      - git_script.sh
  tags:
    - amirplatform
  environment:
    name: production
    url: https://api.amirghedira.com

notify:
  stage: notify
  only:
    refs:
      - /^(main.*)$/
    changes:
      - controllers/**/**
      - middlewares/**/**
      - models/**/**
      - routes/**/**
      - utils/**/**
      - app.js
      - server.js
      - Dockerfile
      - docker-compose-build.yml
      - docker-compose.yml
      - package-lock.json
      - package.json
      - git_script.sh

  tags:
    - amirplatform
  script:
    - chmod +x ./ci/notify.sh
    - ./ci/notify.sh


cleanup:
  stage: cleanup
  only:
    refs:
      - /^(main.*)$/
    changes:
      - controllers/**/**
      - middlewares/**/**
      - models/**/**
      - routes/**/**
      - utils/**/**
      - app.js
      - server.js
      - Dockerfile
      - docker-compose-build.yml
      - docker-compose.yml
      - package-lock.json
      - package.json
      - git_script.sh

  tags:
    - amirplatform
  script:
    - chmod +x ./ci/cleanup.sh
    - ./ci/cleanup.sh