version: '3.3'
services:
  amir_platform_api:
    restart: always
    container_name: amir_platform_api
    image: amir_platform_api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: 
      - .env
    networks:
      - amir_platform
    ports:
      - "5000:5000"


networks:
  amir_platform:
    driver: bridge
