version: '3.3'
services:
  amir_platform_api_prod:
    restart: always
    container_name: amir_platform_api_prod
    image: ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${VERSION}
    networks:
      - amir_platform_api
    env_file: 
      - .env
    ports:
      - "5000:5000"

networks:
  amir_platform_api:
    driver: bridge
