version: '3.3'
services:
  amir_platform_api_prod:
    restart: always
    container_name: amir_platform_api_prod
    image: ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${VERSION}
    volumes:
      - type: bind
        source: /var/log/amir-platform
        target: /app/logs
    networks:
      - amir_platform_api
    env_file: 
      - .env
    ports:
      - "5000:5000"
    deploy:
      resources:
          limits:
            cpus: 0.30
            memory: 150M
          reservations:
            cpus: 0.20
            memory: 140M

networks:
  amir_platform_api:
    driver: bridge
