name: GitlabSync

on:
  - push

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - name: print secrets
      run: |
          echo $DEV_ENV_FILE | base64 -d > .env
          cat .env
      shell: bash
      env:
        DEV_ENV_FILE : ${{secrets.TARGET_TOKEN}}
    - uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        target-url: ${{ secrets.TARGET_URL }}
        target-username: ${{ secrets.TARGET_USERNAME }}
        target-token: ${{ secrets.TARGET_TOKEN }}
